version: '2'
services:
  postgres:
    container_name: neoncity-postgres
    image: postgres
    ports:
     - 10000:5432
    environment:
     - POSTGRES_USER=neoncity
     - POSTGRES_PASSWORD=neoncity
     - POSTGRES_DB=neoncity
  identity:
    container_name: neoncity-identity
    image: neoncity-identity
    build:
      context: ../identity
      args:
       - GEMFURY_USER
       - GEMFURY_API_KEY
    ports:
     - 10001:10000
    links:
     - postgres
    volumes:
     - ../identity/src:/neoncity/pack/src
     - ../identity/migrations:/neoncity/pack/migrations
     - ../identity/node_modules:/neoncity/pack/node_modules     
     - ../identity/secrets.json:/neoncity/var/secrets.json
  core:
    container_name: neoncity-core
    image: neoncity-core
    build:
      context: ../core
      args:
       - GEMFURY_USER
       - GEMFURY_API_KEY
    ports:
     - 10002:10000
    links:
     - postgres
     - identity
    volumes:
     - ../core/src:/neoncity/pack/src
     - ../core/migrations:/neoncity/pack/migrations     
     - ../core/node_modules:/neoncity/pack/node_modules     
     - ../core/secrets.json:/neoncity/var/secrets.json      
  causefe:
    container_name: neoncity-causefe
    image: neoncity-causefe
    build:
      context: ../causefe
      args:
       - GEMFURY_USER
       - GEMFURY_API_KEY
    ports:
     - 10003:10000
    links:
     - postgres
     - identity
     - core
    volumes:
     - ../causefe/src:/neoncity/pack/src
     - ../causefe/node_modules:/neoncity/pack/node_modules
     - ../causefe/secrets.json:/neoncity/var/secrets.json
